
trigger:
- master

pool:
  name: agent1

steps:
- script: git clone https://github.com/IntelliqDevops/maven.git
  displayName: 'ContDownload'
- script: cd /home/azureuser/_work/1/s;mvn package
  displayName: 'ContBuild'
- script: scp /home/azureuser/_work/1/s/webapp/target/webapp.war azureuser@20.63.88.157:/var/lib/tomcat10/webapps/mytestapp.war
  displayName: 'ContDeployment'
- script: git clone https://github.com/IntelliqDevops/FunctionalTesting.git
  displayName: 'Download selenium scripts'
- script: java -jar /home/azureuser/_work/1/s/FunctionalTesting/testing.jar
  displayName: 'Execute selenium script'
- script: scp /home/azureuser/_work/1/s/webapp/target/webapp.war azureuser@4.172.209.183:/var/lib/tomcat10/webapps/myprodapp.war


